@startuml
title UC7 - Choisir lieu de collecte

actor User
participant "RequestController" as RC

User -> RC : choosePickup(intersectionId) (soit dans la carte, un liste ou par nom de rue)
activate RC

RC --> User : pickupSelected (UI updated)
deactivate RC
@enduml
