@startuml
title UC4 - Modifier le nombre de livreurs

actor User
participant "TourController" as TC
participant "TourService" as TS

User -> TC : updateNumCouriers(num)
activate TC

TC -> TS : updateNumCouriers(num)
activate TS

TS -> TS : numCouriers = num
TS -> TS : assignRequestsToCouriers() 
TS --> TC : updatedTours
deactivate TS

TC --> User : "Nombre de livreurs mis à jour"
deactivate TC
@enduml
