@startuml
title UC3 - Importer une liste de requests pour un livreur

actor User
participant "RequestController" as RC
participant "RequestService" as RS
participant "XMLParsers" as XP
participant "TourService" as TS

User -> RC : loadRequests(filepath), optional: List<NewCourrierID>
activate RC

RC -> RS : loadRequests(filepath)
activate RS

RS -> XP : parseRequests(filepath)
activate XP
XP --> RS : PickupDelivery
deactivate XP

RS --> RC : requestsLoaded
deactivate RS

RC -> TS : assignRequestsToCouriers(list<CourierID>)
activate TS
TS -> TS : assignRequestsToCouriers(list<CourierID>)
TS --> RC : toursUpdated
deactivate TS

RC --> User : "Programme chargé et tournées recalculées"
deactivate RC
@enduml
