@startuml
title UC8 - Choisir lieu de livraison

actor User
participant "RequestController" as RC


User -> RC : chooseDelivery(intersectionId) (soit dans la carte, un liste ou par nom de rue)
activate RC


RC --> User : deliverySelected (UI updated)
deactivate RC
@enduml
