@startuml usecase
left to right direction
skinparam packageStyle rectangle

actor "Utilisateur" as User
database "Base de données" as DB


package "Application d'optimisation de tournées de livraison" {

  usecase "Importer un plan (CU1)" as UC1
  usecase "Importer la liste des couriers (CU2)" as UC2
  usecase "Importer une liste de requests pour un livreur (CU3)" as UC3
  usecase "Sauvegarder la liste des requests d'un livreur (CU4)" as UC4
  usecase "Sauvegarder une tournée (CU5)" as UC5
  usecase "Afficher des tournées (CU6)" as UC6
  usecase "Afficher les détails d'une livraison (CU7)" as UC7
  usecase "Afficher la liste des couriers disponibles (CU8)" as UC8
  usecase "Calculer la meilleure tournée (CU9)" as UC9
  usecase "Ajouter une demande de livraison (CU10)" as UC10
  usecase "Supprimer une demande de livraison (CU11)" as UC11
  usecase "Modifier l'ordre des livraisons (CU12)" as UC12
  usecase "Rechercher un RoadSegment (CU13)" as UC13
  usecase "Ajouter l'entrepôt de livraison (CU14)" as UC14

  UC3 .> UC9 : <<includes>>
  UC10 .> UC9 : <<includes>>
  UC11 .> UC9 : <<includes>>
  UC12 .> UC9 : <<includes>>
  UC10 .> UC14 : <<extends>>

  User -- UC1
  User -- UC2
  User -- UC3
  User -- UC4
  User -- UC5
  User -- UC6
  User -- UC7
  User -- UC8
  User -- UC10
  User -- UC11
  User -- UC12
  User -- UC13

  UC1 -- DB
  UC2 -- DB
  UC3 -- DB
  UC4 -- DB
  UC5 -- DB

}
@enduml