@startuml
title UC3 - Importer une liste de requests pour un livreur depuis un fichier

actor User
participant "UI" as UI
participant "RequestController" as RC
participant "PlanningService" as PS
participant "RequestService" as RS
participant "XMLParsers" as XP
participant "TourService" as TS

User -> UI : Charger les requêtes(filepath, CourrierID)
activate UI

UI -> RC : loadRequests(filepath, CourrierID)
activate RC

RC --> PS : courierExists(CourierID)
activate PS

PS --> RC : boolean
deactivate PS

RC -> RS : loadRequests(filepath, CourierID)
activate RS

RS -> XP : parseRequests(filepath, pickupDeliveryToFill)
activate XP

XP --> RS : boolean
deactivate XP

RS --> RC : boolean
deactivate RS

RC -> TS : assignRequestsToCouriers(list<CourierID>)
activate TS
TS -> TS : assignRequestsToCouriers(list<CourierID>)
TS --> RC : toursUpdated
deactivate TS

RC --> UI : "Programme chargé et tournées recalculées"
deactivate RC

UI --> User : Affiche message de succès
deactivate UI
@enduml
