@startuml
title UC - Save Tours to File

actor User
participant "TourController" as TC
participant "TourService" as TS
participant "Tour" as T
participant "XMLWriters" as XW
alt Normal flow
    User -> TC : saveTours(filepath)
    activate TC

    TC -> TS : saveTours(filepath)
    activate TS

    
    TS -> T : getTourData()
    activate T
    T --> TS : tourData
    deactivate T

    TS -> XW : writeTour(tourData, filepath)
    activate XW
    XW --> TS : confirmation
    deactivate XW
    

    TS --> TC : confirmation
    deactivate TS
    TC --> User : "Tours successfully saved"
    deactivate TC
else File system error
    TC --> User : "Error while writing file"
end
@enduml